
name: 'cerebro_dbt'
version: '1.0.0'
config-version: 2

profile: 'cerebro'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  cerebro_dbt:
    # Configures models to be created as tables/views in the specific schema
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

tests:
  cerebro_dbt:
    +severity: warn
