
cerebro:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-datalake
      user: "{{ env_var('DATALAKE_USER', 'admin') }}"
      password: "{{ env_var('DATALAKE_PASSWORD', 'admin') }}"
      port: 5432
      dbname: "{{ env_var('DATALAKE_DB', 'cerebro') }}"
      schema: cerebro
      threads: 1
      keepalives_idle: 0
